# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BagAnalysis.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BagAnalysis.proto',
  package='Atec.BagAnalysis',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x42\x61gAnalysis.proto\x12\x10\x41tec.BagAnalysis\" \n\x0f\x41nalysisRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"s\n\x10\x41nalysisResponse\x12\x30\n\x06result\x18\x01 \x01(\x0e\x32 .Atec.BagAnalysis.AnalysisResult\x12-\n\x05\x66lags\x18\x02 \x03(\x0e\x32\x1e.Atec.BagAnalysis.AnalysisFlag*U\n\x0e\x41nalysisResult\x12\x0e\n\nNoDecision\x10\x00\x12\x11\n\rNoTubRequired\x10\x01\x12\x0f\n\x0bTubDetected\x10\x02\x12\x0f\n\x0bTubRequired\x10\x03*S\n\x0c\x41nalysisFlag\x12\x19\n\x15\x42\x61gHasExtendedHandles\x10\x00\x12\x18\n\x14MultipleBagsDetected\x10\x01\x12\x0e\n\nUprightBag\x10\x02\x32\x65\n\x0b\x42\x61gAnalysis\x12V\n\x07\x41nalyse\x12!.Atec.BagAnalysis.AnalysisRequest\x1a\".Atec.BagAnalysis.AnalysisResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)

_ANALYSISRESULT = _descriptor.EnumDescriptor(
  name='AnalysisResult',
  full_name='Atec.BagAnalysis.AnalysisResult',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NoDecision', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NoTubRequired', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TubDetected', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TubRequired', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=190,
  serialized_end=275,
)
_sym_db.RegisterEnumDescriptor(_ANALYSISRESULT)

AnalysisResult = enum_type_wrapper.EnumTypeWrapper(_ANALYSISRESULT)
_ANALYSISFLAG = _descriptor.EnumDescriptor(
  name='AnalysisFlag',
  full_name='Atec.BagAnalysis.AnalysisFlag',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BagHasExtendedHandles', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MultipleBagsDetected', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UprightBag', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=277,
  serialized_end=360,
)
_sym_db.RegisterEnumDescriptor(_ANALYSISFLAG)

AnalysisFlag = enum_type_wrapper.EnumTypeWrapper(_ANALYSISFLAG)
NoDecision = 0
NoTubRequired = 1
TubDetected = 2
TubRequired = 3
BagHasExtendedHandles = 0
MultipleBagsDetected = 1
UprightBag = 2



_ANALYSISREQUEST = _descriptor.Descriptor(
  name='AnalysisRequest',
  full_name='Atec.BagAnalysis.AnalysisRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='Atec.BagAnalysis.AnalysisRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=71,
)


_ANALYSISRESPONSE = _descriptor.Descriptor(
  name='AnalysisResponse',
  full_name='Atec.BagAnalysis.AnalysisResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='Atec.BagAnalysis.AnalysisResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flags', full_name='Atec.BagAnalysis.AnalysisResponse.flags', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=188,
)

_ANALYSISRESPONSE.fields_by_name['result'].enum_type = _ANALYSISRESULT
_ANALYSISRESPONSE.fields_by_name['flags'].enum_type = _ANALYSISFLAG
DESCRIPTOR.message_types_by_name['AnalysisRequest'] = _ANALYSISREQUEST
DESCRIPTOR.message_types_by_name['AnalysisResponse'] = _ANALYSISRESPONSE
DESCRIPTOR.enum_types_by_name['AnalysisResult'] = _ANALYSISRESULT
DESCRIPTOR.enum_types_by_name['AnalysisFlag'] = _ANALYSISFLAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalysisRequest = _reflection.GeneratedProtocolMessageType('AnalysisRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANALYSISREQUEST,
  '__module__' : 'BagAnalysis_pb2'
  # @@protoc_insertion_point(class_scope:Atec.BagAnalysis.AnalysisRequest)
  })
_sym_db.RegisterMessage(AnalysisRequest)

AnalysisResponse = _reflection.GeneratedProtocolMessageType('AnalysisResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANALYSISRESPONSE,
  '__module__' : 'BagAnalysis_pb2'
  # @@protoc_insertion_point(class_scope:Atec.BagAnalysis.AnalysisResponse)
  })
_sym_db.RegisterMessage(AnalysisResponse)



_BAGANALYSIS = _descriptor.ServiceDescriptor(
  name='BagAnalysis',
  full_name='Atec.BagAnalysis.BagAnalysis',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=362,
  serialized_end=463,
  methods=[
  _descriptor.MethodDescriptor(
    name='Analyse',
    full_name='Atec.BagAnalysis.BagAnalysis.Analyse',
    index=0,
    containing_service=None,
    input_type=_ANALYSISREQUEST,
    output_type=_ANALYSISRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BAGANALYSIS)

DESCRIPTOR.services_by_name['BagAnalysis'] = _BAGANALYSIS

# @@protoc_insertion_point(module_scope)
