# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import BagAnalysis_pb2 as BagAnalysis__pb2


class BagAnalysisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyse = channel.stream_stream(
                '/Atec.BagAnalysis.BagAnalysis/Analyse',
                request_serializer=BagAnalysis__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=BagAnalysis__pb2.AnalysisResponse.FromString,
                )


class BagAnalysisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Analyse(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BagAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyse': grpc.stream_stream_rpc_method_handler(
                    servicer.Analyse,
                    request_deserializer=BagAnalysis__pb2.AnalysisRequest.FromString,
                    response_serializer=BagAnalysis__pb2.AnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Atec.BagAnalysis.BagAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BagAnalysis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Analyse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Atec.BagAnalysis.BagAnalysis/Analyse',
            BagAnalysis__pb2.AnalysisRequest.SerializeToString,
            BagAnalysis__pb2.AnalysisResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
